### ISSUE TITLE
Authconfig OS Specific Changes

### ISSUE THREAD

**Issue by sapiensantiquus** [intuitivetechnologygroup/authconfig-formula#15]
Basically RHEL 7 requires port 88 to be specified according to Adobe's shell script

RHEL 7:
authconfig \
‐‐krb5realm=ADOBENET.GLOBAL.ADOBE.COM \
‐‐disablekrb5kdcdns \
‐‐disablekrb5realmdns \
‐‐krb5kdc=globalad.corp.adobe.com:88 \
‐‐krb5adminserver=globalad.corp.adobe.com \
‐‐update

RHEL 6:
authconfig \
‐‐krb5realm=ADOBENET.GLOBAL.ADOBE.COM \
‐‐disablekrb5kdcdns \
‐‐disablekrb5realmdns \
‐‐krb5kdc=globalad.corp.adobe.com \
‐‐krb5adminserver=globalad.corp.adobe.com \
‐‐update

**Comment by simplyadrian** [comment]
closed with latest commit
